<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQHeR0zt\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQHeR0zt/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQHeR0zt.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQHeR0zt\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerQHeR0zt\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'QHeR0zt',
    'container.build_id' => '23d8b303',
    'container.build_time' => 1727077414,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQHeR0zt');
