<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKhbRj9\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKhbRj9/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXKhbRj9.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXKhbRj9\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerXKhbRj9\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'XKhbRj9',
    'container.build_id' => '7663262a',
    'container.build_time' => 1727060611,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKhbRj9');
