<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5rh4Zzj\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5rh4Zzj/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/Container5rh4Zzj.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\Container5rh4Zzj\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \Container5rh4Zzj\SimpleSAML_KernelProdContainer([
    'container.build_hash' => '5rh4Zzj',
    'container.build_id' => '4d22b386',
    'container.build_time' => 1727684941,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5rh4Zzj');
